### Enpoint pour envoyer une demande de parrainage à un admin
POST http://localhost:3000/demande-invitation
Content-Type: application/json
Set-Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1ZWFjYWFhN2Y3MzllY2YxNTM5ZDdiMSIsImVtYWlsIjoibWFydmluLm1vcmluQGluc3RpdHV0c29sYWNyb3VwLmNvbSIsIm5hbWUiOiJNYXJ2aW4gTW9yaW4iLCJ0ZWwiOiIwMTIzNDU2Nzg5IiwiaXNfYWRtaW4iOnRydWUsInJlc2VydmF0aW9ucyI6W10sIl9fdiI6MH0sImlhdCI6MTcxMDI1MzgzMX0.YaQUHbhrtx7BtitOyfIlSnrDe7h01vIprLEueIPFunY; Path=/; HttpOnly

{
  "name": "Morin Marvin",
  "email": "marvin.malouin@gmail.com",
  "tel": "123456789"
}