### Enpoint pour ajouter un équipement
POST http://localhost:3000/equipement
Content-Type: application/json

{
    "name" : "Chauffage"
}





### Enpoint pour récupérer tous les équipements
GET http://localhost:3000/equipement





### Enpoint pour mettre à jour un équipement par son id
PUT http://localhost:3000/equipement/65e6f8d89d1d89c4e4095c34
Content-Type: application/json

{
    "name" : "Climatisateur"
}




### Enpoint pour Mettre à jour tous les équipements
PUT http://localhost:3000/equipement
Content-Type: application/json

{
  "name": "Cafetière"
}





### Enpoint pour supprimer un équipement par son ID
DELETE http://localhost:3000/equipement/65e6f8d89d1d89c4e4095c34





### Enpoint pour supprimer tous les équipements
DELETE http://localhost:3000/equipement





### Enpoint pour Récupérer les détails d'un équipement
GET http://localhost:3000/equipement/65e82d6ff6e3bf9c1e9680ad