### Enpoint pour créer un nouveau logement
POST http://localhost:3000/logement/ajouter-logement
Content-Type: application/json

{
  "images": ["image1.jpg", "image2.jpg"],
  "secteur": "Quartier A",
  "description": "Description du logement",
  "tarif_bas": 100,
  "tarif_moyen": 150,
  "tarif_haut": 200,
  "m_carre": 80,
  "chambre": 2,
  "salle_de_bain": 1,
  "categorie": "Appartement",
  "type": "T2",
  "equipements": ["wifi", "climatisation"],
    "adulte": 2,
  "enfant": 1,
  "animeaux": 1
}

### Enpoint pour créer un nouveau logement
POST http://localhost:3000/logement/ajouter-logement
Content-Type: application/json

{
  "images": ["image1.jpg", "image2.jpg"],
  "secteur": "Quartier B",
  "description": "Description du logement",
  "tarif_bas": 200,
  "tarif_moyen": 450,
  "tarif_haut": 900,
  "m_carre": 70,
  "chambre": 2,
  "salle_de_bain": 2,
  "categorie": "Atipyque",
  "type": "T3",
  "equipements": ["Bateau à moteur", "Bateau à voile"],
    "adulte": 1,
  "enfant": 0,
  "animeaux": 1
}

### Enpoint pour créer un nouveau logement
POST http://localhost:3000/logement/ajouter-logement
Content-Type: application/json

{
  "images": ["image1.jpg", "image2.jpg"],
  "secteur": "Quartier B",
  "description": "Description du logement",
  "tarif_bas": 200,
  "tarif_moyen": 250,
  "tarif_haut": 300,
  "m_carre": 50,
  "chambre": 1,
  "salle_de_bain": 1,
  "categorie": "Chalet",
  "type": "T2",
  "equipements": ["Centre equestre", "Golf"],
    "adulte": 2,
  "enfant": 0,
  "animeaux": 0
}

### Enpoint pour créer un nouveau logement
POST http://localhost:3000/logement/ajouter-logement
Content-Type: application/json

{
  "images": ["image1.jpg", "image2.jpg"],
  "secteur": "Quartier C",
  "description": "Description du logement",
  "tarif_bas": 500,
  "tarif_moyen": 750,
  "tarif_haut": 900,
  "m_carre": 120,
  "chambre": 4,
  "salle_de_bain": 1,
  "categorie": "Maison",
  "type": "T5",
  "equipements": ["Jaccuzi", "Golf"],
    "adulte": 1,
  "enfant": 1,
  "animeaux": 1
}

### Enpoint pour créer un nouveau logement
POST http://localhost:3000/logement/ajouter-logement
Content-Type: application/json

{
  "images": ["image1.jpg", "image2.jpg"],
  "secteur": "Quartier D",
  "description": "Description du logement",
  "tarif_bas":650,
  "tarif_moyen": 850,
  "tarif_haut": 1050,
  "m_carre": 150,
  "chambre": 4,
  "salle_de_bain": 2,
  "categorie": "Manoir",
  "type": "T4",
  "equipements": ["Parc de jeu", "Patinoire", "Piscine"],
    "adulte": 1,
  "enfant": 1,
  "animeaux": 1
}

### Enpoint pour créer un nouveau logement
POST http://localhost:3000/logement/ajouter-logement
Content-Type: application/json

{
  "images": ["image1.jpg", "image2.jpg"],
  "secteur": "Quartier A",
  "description": "Description du logement",
  "tarif_bas":6050,
  "tarif_moyen": 7050,
  "tarif_haut": 8050,
  "m_carre": 550,
  "chambre": 15,
  "salle_de_bain": 10,
  "categorie": "Villa",
  "type": "T25",
  "equipements": ["Piste de bobsleigh", "Plongée", "Spa", "Sport d'hiver", "Tennis", "Piscine"],
    "adulte": 3,
  "enfant": 2,
  "animeaux": 0
}

### Enpoint pour créer un nouveau logement
POST http://localhost:3000/logement/ajouter-logement
Content-Type: application/json

{
  "images": ["image1.jpg", "image2.jpg"],
  "secteur": "Quartier B",
  "description": "Description du logement",
  "tarif_bas": 200,
  "tarif_moyen": 250,
  "tarif_haut": 300,
  "m_carre": 50,
  "chambre": 1,
  "salle_de_bain": 1,
  "categorie": "Chalet",
  "type": "T2",
  "equipements": ["Centre equestre", "Golf"],
  "adulte": 2,
  "enfant": 1,
  "animeaux": 1
}






### Enpoint pour obtenir tous les details d'un logement par son id 
GET http://localhost:3000/logement/get-logement-details/65dddfee0ead76b43f534e2b





### Endpoint pour modifier les informations / mettre à jour un logmement par son id
PUT http://localhost:3000/logement/update-logement-details/65dddfee0ead76b43f534e2b
Content-Type: application/json

{
  "tarif_haut": 250
}





### Enpoint pour modifier tous les logements
PUT http://localhost:3000/logement/update-all-logements
Content-Type: application/json

{
    "description": "Nouvelle description pour tous les logements",
    "tarif_bas": 120,
    "tarif_moyen": 170,
    "tarif_haut": 220
}





### Endpoint pour supprimer un logement par son id
DELETE http://localhost:3000/logement/delete-logement/65dda4492d699c32bd6c5e01





### Endpoint pour supprimer tous les logements
DELETE http://localhost:3000/logement/delete-all-logements





### Endpoint pour récupérer les réservations d'un logement par son id
GET http://localhost:3000/logement/reservation-logement/65dddfee0ead76b43f534e2b










//     RECHERCHE    //

### Enpoint pour rechercher logement avec critères prix
POST http://localhost:3000/logement/recherche-logement
Content-Type: application/json

{
  "tarif_bas": 160
}

### Enpoint pour rechercher logement avec critères prix
POST http://localhost:3000/logement/recherche-logement
Content-Type: application/json

{
  "tarif_moyen": 250
}

### Enpoint pour rechercher logement avec critères prix
POST http://localhost:3000/logement/recherche-logement
Content-Type: application/json

{
  "tarif_haut": 310
}

### Enpoint pour rechercher logement avec critères
POST http://localhost:3000/logement/recherche-logement
Content-Type: application/json

{
    "secteur": "Quartier B"
}

### Rechercher des logements par plusieurs critères
POST http://localhost:3000/logement/recherche-logement
Content-Type: application/json

{
    "secteur": "Quartier B",
    "tarif_bas": 200,
    "chambre": 1,
    "categorie": "Chalet",
    "type": "T2"
}

### Rechercher des logements avec équipements spécifiques
POST http://localhost:3000/logement/recherche-logement
Content-Type: application/json

{
    "equipements": ["Centre equestre", "Golf"]
}

### Rechercher des logements avec des animeaux
POST http://localhost:3000/logement/recherche-logement
Content-Type: application/json

{
  "animeaux": 2
}

### Rechercher des logements avec des animeaux, enfant, adulte
POST http://localhost:3000/logement/recherche-logement
Content-Type: application/json

{
  "adulte": 3,
  "enfant": 3,
  "animeaux": 1
  }
