### Enpoint pour créer un nouveau logement
POST http://localhost:3000/logement/ajouter-logement
Content-Type: application/json

{
  "images": ["image1.jpg", "image2.jpg"],
  "secteur": "Quartier A",
  "description": "Description du logement",
  "tarif_bas": 100,
  "tarif_moyen": 150,
  "tarif_haut": 200,
  "m_carre": 80,
  "chambre": 2,
  "salle_de_bain": 1,
  "categorie": "Appartement",
  "type": "T2",
  "equipements": ["wifi", "climatisation"]
}

### Enpoint pour créer un nouveau logement
POST http://localhost:3000/logement/ajouter-logement
Content-Type: application/json

{
  "images": ["image1.jpg", "image2.jpg"],
  "secteur": "Quartier B",
  "description": "Description du logement",
  "tarif_bas": 200,
  "tarif_moyen": 450,
  "tarif_haut": 900,
  "m_carre": 120,
  "chambre": 3,
  "salle_de_bain": 1,
  "categorie": "Appartement",
  "type": "T3",
  "equipements": ["wifi", "climatisation"]
}





### Enpoint pour obtenir tous les details d'un logement par son id 
GET http://localhost:3000/logement/get-logement-details/65dddfee0ead76b43f534e2b





### Endpoint pour modifier les informations / mettre à jour un logmement par son id
PUT http://localhost:3000/logement/update-logement-details/65dddfee0ead76b43f534e2b
Content-Type: application/json

{
  "tarif_haut": 250
}





### Enpoint pour modifier tous les logements
PUT http://localhost:3000/logement/update-all-logements
Content-Type: application/json

{
    "description": "Nouvelle description pour tous les logements",
    "tarif_bas": 120,
    "tarif_moyen": 170,
    "tarif_haut": 220
}





### Endpoint pour supprimer un logement par son id
DELETE http://localhost:3000/logement/delete-logement/65dda4492d699c32bd6c5e01





### Endpoint pour supprimer tous les logements
DELETE http://localhost:3000/logement/delete-all-logements





### Endpoint pour récupérer les réservations d'un logement par son id
GET http://localhost:3000/logement/reservation-logement/65dddfee0ead76b43f534e2b





### Endpoint pour récupérer tous les logements
GET http://localhost:3000/logement/get_all_logements