### Créer une nouvelle note
POST http://localhost:3000/rating/add-note
Content-Type: application/json

{
  "rated": 5,
  "text": "Excellent service !",
  "logement_id": "65dddfee0ead76b43f534e2b",
  "reservation_id": "65df2d1260571506d834c018",
  "user_id": "65ddbf57b6c2c234feca050e"
}




### Enpoint pour récupérer toutes les notes
GET http://localhost:3000/rating/all-ratings
Content-Type: application/json




### Enpoint pour modifier une note avec son id
PUT http://localhost:3000/rating/update-rating/65df2d2060571506d834c01d
Content-Type: application/json

{
    "rated": 4, 
    "text": "Très bien !" 
}




### Enpoint pour mettre à jours toutes les notes
PUT http://localhost:3000/rating/update-all-ratings
Content-Type: application/json

{
    "rated": 3, 
    "text": "Bien."
}





### Enpoint pour supprimer une note par son ID
DELETE http://localhost:3000/rating/delete-rating/65df3193bde68e2f229a53b5





### Enpoint pour supprimer toutes les notes
DELETE http://localhost:3000/rating/delete-all-ratings





### Enpoint pour récupérer les informations d'une note avec son id
GET http://localhost:3000/rating/get-infos-rating/65df3193bde68e2f229a53b5