
### Enpoint pour ajouter une reservation
POST http://localhost:3000/reservation/ajouter-reservation
Content-Type: application/json
Set-Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1ZGRiZjU3YjZjMmMyMzRmZWNhMDUwZSIsImVtYWlsIjoibm91dmVsX3V0aWxpc2F0ZXVyQGV4YW1wbGUuY29tIiwibmFtZSI6Ik5vdXZlbCBVdGlsaXNhdGV1ciIsInRlbCI6IjAxMjM0NTY3ODkiLCJwYXNzd29yZCI6IiQyYiQxMCRtaXdMMkQvN0E2aTU5SnFvUzRpZkplZzVzNzVXLkJMQnpPWnR5ZkxBcGF1UDBOem9wellwMiIsImlzX2FkbWluIjp0cnVlLCJfX3YiOjB9LCJpYXQiOjE3MDkxMTI4OTR9.I_61Z4dGKZirQmkMq91Q8NSuZevTsK1dtr58_Gu46LA; Path=/; HttpOnly

{
  "start_date": "2024-03-01",
  "end_date": "2024-03-05",
  "chef_cuisine": true,
  "visite": "2024-02-28",
  "logement_id": "65dddfee0ead76b43f534e2b",
  "user_id": "65ddbf57b6c2c234feca050e"
}





### Enpoint pour ajouter une reservation
POST http://localhost:3000/reservation/ajouter-reservation
Content-Type: application/json
Set-Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1ZGRiZjU3YjZjMmMyMzRmZWNhMDUwZSIsImVtYWlsIjoibm91dmVsX3V0aWxpc2F0ZXVyQGV4YW1wbGUuY29tIiwibmFtZSI6Ik5vdXZlbCBVdGlsaXNhdGV1ciIsInRlbCI6IjAxMjM0NTY3ODkiLCJwYXNzd29yZCI6IiQyYiQxMCRtaXdMMkQvN0E2aTU5SnFvUzRpZkplZzVzNzVXLkJMQnpPWnR5ZkxBcGF1UDBOem9wellwMiIsImlzX2FkbWluIjp0cnVlLCJfX3YiOjB9LCJpYXQiOjE3MDkwMzk2NjJ9.25EJMxWfNx1QRKbJctm3F_wNApEjAWHee_EQk9ZRZaY; Path=/; HttpOnly

{
  "start_date": "2024-07-15",
  "end_date": "2024-07-30",
  "chef_cuisine": false,
  "visite": "2024-07-10",
  "logement_id": "65dda4492d699c32bd6c5e01",
  "user_id": "65ddbf57b6c2c234feca050e"
}





### Enpoint pour obtenir toutes les réservations
GET http://localhost:3000/reservation/all-reservation





### Enpoint pour obtenir les details des informations d'une reservation par son id
GET http://localhost:3000/reservation/get-reservation-details/65ddf43f2cef50e36910084c





### Enpoint pour mettre à jour les détails d'une réservation par son id
PUT http://localhost:3000/reservation/update-reservation-details/65ddf43f2cef50e36910084c
Content-Type: application/json

{
    "chef_cuisine": false
}





### Endpoint pour mettre à jour toutes les réservations
PUT http://localhost:3000/reservation/update-all-reservations
Content-Type: application/json

{
  "chef_cuisine": true
}





### Enpoint pour supprimer une reservation par son id
DELETE http://localhost:3000/reservation/delete-reservation/65defe51bc69d602f52cc10f





### Enpoint pour suprier toutes les réservations
DELETE http://localhost:3000/reservation/delete-all-reservations





### Enpoint pour Récupérer les notes d'une réservation par son id
GET http://localhost:3000/reservation/get-reservation-rating/