### Endpoint pour la Création d'un utilisateur
POST http://localhost:3000/user/ajout-user
Content-Type: application/json

{
  "email": "nouvel_utilisateur@example.com",
  "name": "Nouvel Utilisateur",
  "tel": "0123456789",
  "password": "1234",
  "is_admin": false
}




### Endpoint pour Obtenir tous les utilisateurs
GET http://localhost:3000/user/get-all-users





### Endpoint pour Modifier les informations des utilisateurs en bloc (ici 1 bloc "{}")
PUT http://localhost:3000/user/update-users-bloc
Content-Type: application/json

[
  {
    "_id": "65dda50b2d699c32bd6c5e05",
    "email": "nouveau_email2@example.com",
    "name": "Nouveau Nom 1",
    "tel": "091011121314",
    "password": "1234",
    "is_admin": true
  }
]





### Endpoint pour Supprimer tous les utilisateurs
DELETE http://localhost:3000/user/delete-all-users





### Endpoint pour Supprimer un utilisateur par son id
DELETE http://localhost:3000/user/delete-user/65ddbe6bd27c43f23aa17128





### Endpoint pour Rechercher un utilisateur via son id (Récupérer les détails du user)
GET http://localhost:3000/user/get-user-by-id/65dc8af62a171e3d79d95ebc





### Endpoint pour Modifier les informations d'un utilisateur par son id
PUT http://localhost:3000/user/update-users/65ddbf57b6c2c234feca050e
Content-Type: application/json

  {
  "email": "nouvel_utilisateur@example.com",
  "name": "Nouvel Utilisateur",
  "tel": "0123456789",
  "password": "12345",
  "is_admin": true
  }





### Endpoint pour CONNEXION USER
GET http://localhost:3000/user/login-user
Content-Type: application/json

{
  "email": "nouvel_utilisateur@example.com",
  "password": "12345"
}





### Endpoint pour récupérer les informations d'un utilisateur connecté
GET http://localhost:3000/user/get-logged-in-user





### Endpoint pour deconnecter un user
GET http://localhost:3000/user/logout-user





### Enpoint pour récupérer la / les réservation(s) d'un user
GET http://localhost:3000/user/65ddbf57b6c2c234feca050e/reservation