### Endpoint pour la Création d'un utilisateur
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "marvin.malouin@gmail.com",
  "name": "Marvin Morin",
  "tel": "0123456789",
  "password": "12345",
  "is_admin": true
}





### Endpoint pour Obtenir tous les utilisateurs
GET http://localhost:3000/user





### Endpoint pour Modifier les informations des utilisateurs en bloc (ici 1 bloc "{}")
PUT http://localhost:3000/user
Content-Type: application/json

[
  {
    "_id": "65e72dcfe6339dfd13e6a075",
    "email": "nouveau_email2@example.com",
    "name": "Nouveau Nom 1",
    "tel": "091011121314",
    "password": "1234",
    "is_admin": true
  }
]





### Endpoint pour Supprimer tous les utilisateurs
DELETE http://localhost:3000/user





### Endpoint pour Supprimer un utilisateur par son id
DELETE http://localhost:3000/user/65e72dcfe6339dfd13e6a075





### Endpoint pour Rechercher un utilisateur via son id (Récupérer les détails du user)
GET http://localhost:3000/user/65e724c972567dd0e1a29b44





### Endpoint pour Modifier les informations d'un utilisateur par son id
PUT http://localhost:3000/user/65eacaaa7f739ecf1539d7b1
Content-Type: application/json

  {
  
  "name": "Marvin Morin",
  "tel": "0123456789",
  "password": "12345",
  "is_admin": true
  }





### Endpoint pour la connexion d'un utilisateur 
GET http://localhost:3000/auth
Content-Type: application/json

{
  "email": "marvin.malouin@gmail.com",
  "password": "12345"
}





### Endpoint pour récupérer les informations d'un utilisateur connecté
GET http://localhost:3000/auth/get-logged-in-user





### Endpoint pour deconnecter un user
GET http://localhost:3000/auth/logout





### Enpoint pour récupérer la / les réservation(s) d'un user
GET http://localhost:3000/user/65ddbf57b6c2c234feca050e/reservation